#This file contains useful data for the hangman game

nbr_shot=8  #number ofshot per game

name_file_scores= "scores" #name of the file storing the scores

list_words=["banana",
            "Cherry",
            "apple",
            "murder",
            "cupboard",
            "spoon",
            "plate", 
            "salad", 
            "tomato", 
            "joy", 
            "friends", 
            "bread", 
            "table",
            "window", 
            "curtain", 
            "boat", 
            "ship", 
            "pirate", 
            "princess", 
            "dragon",
            "story", 
            "hanged",
            "pink", 
            "red", 
            "blue", 
            "black", 
            "yellow", 
            "green", 
            "scooter", 
            "bicycle", 
            "car", 
            "weather", 
            "rain", 
            "storm",
            "sun", 
            "barbecue", 
            "cheese", 
            "fork", 
            "mountain", 
            "sea",
            "heat", 
            "cold"]